#!/usr/bin/env python3
"""Analyse the Tascam 424 MKIII channel Baxandall EQ (U202B, MIX PCB 2/4) and emit a lookup table
of first-order shelf parameters, so the plugin can reproduce its bass / treble behaviour.

Netlist (read from the service-manual schematic):
  R216 18k : Vin  - L          R219 18k : Vout - R
  C213 .015u : L - M           C215 .015u : M - R
  R24 100k bass pot : L -(w)- M - R   wiper -> M          (wiper w measured from the L / input end)
  R218 5.6k : M - X(virtual ground)
  R23 100k treble pot : Vin -(w)- P - Vout, wiper P
  C214 .0033u + R217 5.6k : P - X
"""
import numpy as np

R216 = R219 = 18e3
R218 = R217 = 5.6e3
C213 = C215 = 0.015e-6
C214 = 0.0033e-6
RB = RT = 100e3

def solve(f, wb, wt):
    s = 2j * np.pi * f
    g = lambda r: 1.0 / r
    eps = 1e-3                                  # avoid zero-ohm pot halves
    rba, rbb = max(wb, eps) * RB, max(1 - wb, eps) * RB
    rta, rtb = max(wt, eps) * RT, max(1 - wt, eps) * RT
    zc214 = 1.0 / (s * C214) + R217
    # unknown vector: L, M, R, P, Vout ; Vin = 1 ; X = 0
    A = np.zeros((5, 5), complex); b = np.zeros(5, complex)
    # KCL at L
    A[0, 0] = g(R216) + s * C213 + g(rba); A[0, 1] = -(s * C213 + g(rba)); b[0] = g(R216)
    # KCL at M
    A[1, 0] = -(s * C213 + g(rba)); A[1, 1] = s * C213 + g(rba) + s * C215 + g(rbb) + g(R218); A[1, 2] = -(s * C215 + g(rbb))
    # KCL at R
    A[2, 1] = -(s * C215 + g(rbb)); A[2, 2] = s * C215 + g(rbb) + g(R219); A[2, 4] = -g(R219)
    # KCL at P
    A[3, 3] = g(rta) + g(rtb) + 1 / zc214; A[3, 4] = -g(rtb); b[3] = g(rta)
    # KCL at X (virtual ground): currents from M via R218, from P via zc214 sum to zero
    A[4, 1] = g(R218); A[4, 3] = 1 / zc214
    x = np.linalg.solve(A, b)
    return x[4]

freqs = np.geomspace(20, 20000, 200)
def resp(wb, wt): return np.array([20 * np.log10(abs(solve(f, wb, wt))) for f in freqs])

def shelf_low(f, gdb, fm):
    g0 = 10 ** (gdb / 20); wm = 2 * np.pi * fm; wz = wm * np.sqrt(g0); wp = wm / np.sqrt(g0)
    s = 2j * np.pi * f; return 20 * np.log10(abs((s + wz) / (s + wp)))
def shelf_high(f, gdb, fm):
    g = 10 ** (gdb / 20); wm = 2 * np.pi * fm; wz = wm / np.sqrt(g); wp = wm * np.sqrt(g)
    s = 2j * np.pi * f; return 20 * np.log10(abs(g * (s + wz) / (s + wp)))

def fit(curve, kind):
    # asymptote gain from the far end of the band, then grid-search the mid frequency
    g = curve[0] - curve[-1] if kind == "low" else curve[-1] - curve[0]
    ref = curve[-1] if kind == "low" else curve[0]
    best = (1e9, 1000)
    for fm in np.geomspace(30, 12000, 160):
        m = (shelf_low if kind == "low" else shelf_high)(freqs, g, fm)
        err = np.sqrt(np.mean((m + ref - curve) ** 2))
        if err < best[0]: best = (err, fm)
    return g, best[1], best[0], ref

if __name__ == "__main__":
    pos = np.linspace(0, 1, 21)
    # sanity: centre must be flat
    c = resp(0.5, 0.5); print("centre flatness (dB range): %.3f" % (c.max() - c.min()), " level %.2f dB" % c.mean())
    rows_b, rows_t = [], []
    print("\nBASS (wiper from input end)   pos  gain_dB  f_mid   rms_err")
    for w in pos:
        cur = resp(w, 0.5); g, fm, e, ref = fit(cur - c.mean(), "low"); rows_b.append((g, fm)); print(f"   {w:4.2f}  {g:7.2f}  {fm:7.0f}  {e:5.2f}")
    print("\nTREBLE (wiper from input end)  pos  gain_dB  f_mid   rms_err")
    for w in pos:
        cur = resp(0.5, w); g, fm, e, ref = fit(cur - c.mean(), "high"); rows_t.append((g, fm)); print(f"   {w:4.2f}  {g:7.2f}  {fm:7.0f}  {e:5.2f}")

    # knob 0 = full cut, 0.5 = flat, 1 = full boost  (pot position w = 1 - knob)
    def emit(name, rows):
        r = rows[::-1]
        g = ", ".join("%.3ff" % x[0] for x in r); f = ", ".join("%.1ff" % x[1] for x in r)
        return f"    static constexpr float {name}Gain[21] = {{ {g} }};\n    static constexpr float {name}Freq[21] = {{ {f} }};\n"
    hdr = ("#pragma once\n// GENERATED by tools/gen_baxandall.py from the Tascam 424 MKIII Baxandall EQ netlist. Do not edit.\n"
           "// 21 knob positions (0 = full cut, 0.5 = flat, 1 = full boost): first-order shelf gain (dB) and midpoint frequency (Hz).\n"
           "namespace portastudio\n{\nstruct BaxandallTable\n{\n" + emit("bass", rows_b) + emit("treble", rows_t) + "};\n}\n")
    open("Source/PortaEq.h", "w").write(hdr); print("\nwrote Source/PortaEq.h")
