#pragma once
// GENERATED by tools/gen_baxandall.py from the Tascam 424 MKIII Baxandall EQ netlist. Do not edit.
// 21 knob positions (0 = full cut, 0.5 = flat, 1 = full boost): first-order shelf gain (dB) and midpoint frequency (Hz).
namespace portastudio
{
struct BaxandallTable
{
    static constexpr float bassGain[21] = { -16.117f, -13.668f, -11.578f, -9.756f, -8.116f, -6.606f, -5.189f, -3.839f, -2.536f, -1.261f, 0.000f, 1.261f, 2.536f, 3.839f, 5.189f, 6.606f, 8.116f, 9.756f, 11.578f, 13.668f, 16.117f };
    static constexpr float bassFreq[21] = { 229.5f, 197.4f, 176.3f, 163.5f, 151.6f, 146.0f, 146.0f, 140.6f, 140.6f, 135.4f, 197.4f, 135.4f, 140.6f, 140.6f, 146.0f, 146.0f, 151.6f, 163.5f, 176.3f, 197.4f, 229.5f };
    static constexpr float trebleGain[21] = { -14.989f, -9.996f, -7.278f, -5.523f, -4.256f, -3.271f, -2.462f, -1.766f, -1.142f, -0.561f, 0.000f, 0.561f, 1.142f, 1.766f, 2.462f, 3.271f, 4.256f, 5.523f, 7.278f, 9.996f, 14.989f };
    static constexpr float trebleFreq[21] = { 2760.2f, 1823.6f, 1349.0f, 1076.0f, 925.4f, 826.5f, 738.2f, 684.6f, 659.3f, 634.9f, 197.4f, 634.9f, 659.3f, 684.6f, 738.2f, 826.5f, 925.4f, 1076.0f, 1349.0f, 1823.6f, 2760.2f };
};
}
